### ISSUE TITLE
Графики

### ISSUE THREAD

**Issue by Sivolday** [TheLuckyChip/LuckyBox#2]
Одновременный вывод показаний температур на одном графике с пользованием [Plotly.js](https://plot.ly/javascript/)

**Comment by TheLuckyChip** [comment]
Спасибо. Только пожалуйста дождитесь когда Сергей закончит апдейт нового интерфейса. А то тяжело будет склеивать. Интерфейс почти готов, мы его обсудили и нашли несколько помарок. Сергей последние штрихи вносит, как я понял.

**Comment by Sivolday** [comment]
Если ждать, то теряется смысл параллельной разработки. Проблем со слиянием не будет, я периодически актуализирую свою ветку.

Третьестепенных веток боятся не нужно, они могут быть даже мусорными и вообще не вливаться в основную, к примеру, если сообщество не одобрило изменения. Коммитов в этих ветках должно быть много, это позволяет видеть движение друг друга и не взяться одновременно за один фронт работ.

**Comment by mitskovets** [comment]
Согласен, не проблема слить. И там не так много кода, что бы в нем запутаться.

**Comment by Sivolday** [comment]
[Промежуточный результат](https://youtu.be/6Fts3wOpqOw)

**Comment by TheLuckyChip** [comment]
Красота! Супер, только до двух знаков можно округлить показания (если это возможно не ковыряя исходную библиотеку). А что за библиотека?

**Comment by Sivolday** [comment]
В первом приближении с графиками закончил, думал, будет сложнее. Либа вот [эта](https://www.highcharts.com) насколько я понял для opensource она бесплатная.
Выглядит теперь вот [так](https://youtu.be/bAolhiprqh4)

**Comment by TheLuckyChip** [comment]
Мега круто. Это можно просто под всеми вкладками разместить. Т.е. Дист, Рект, Затирание - выбери что хочешь))
Надо Сергея попросить добавить в веб-интерфейс

**Comment by TheLuckyChip** [comment]
Вроде в соседнем треде о json формате договорились и о Get тоже. Надо теперь договориться кто что конкретно делает.

**Comment by Sivolday** [comment]
Прикрутил (в первом приближении) графики и нормальное получения данных с датчиков.

Всё очень пока сыро. Сейчас захардкордил 4 шт, не уверен что с меньшим числом заведётся.

![plots](https://user-images.githubusercontent.com/30410315/39749106-0f4d1ad4-52dc-11e8-9e63-00292edff8d8.png)

**Comment by TheLuckyChip** [comment]
Выглядит красиво.

**Comment by Sivolday** [comment]
Затестите кто-нибудь, заведется, нет.

**Comment by Sivolday** [comment]
Натарулся на статью https://habr.com/post/354754/ именно этот паттерн я предлагаю использовать.

**Comment by TheLuckyChip** [comment]
Затестить смогу не ранее 10-ого вечера или ночи. Какой-то насыщенный график перемещений получается((. 
А статья правильная. Классический паблишер-сабскрайбер, и он очень нам поможет когда MQTT будем добавлять! Полностью данный подход поддерживаю.

**Comment by serjrv** [comment]
Давайте сразу с масштабом вывода определимся, а то править потом "геморно" будет. Я на TFT дисплее уже прикинул в реальности что и как. В WEB не силен, но было бы очень удобно видеть температуру в кубе и выход из дефлегматора за **весь** период на текущем графике, а температуру в царге и на выходе, в развернутом виде текущей временной выборки. Это думаю по запросу из основного кода программы выдам без проблем. Далее, масштаб по Y не для всех графиков нужен до сотых, соответственно пропорции нужно придумать. Как пример, я на форуме писал в каких пропорциях и что вывожу на TFT дисплей.
И еще вопрос, а с сокетами ESP не дружит, а то post, get... Это просто как ламер спросил, т.к. вроде проще для быстрого обмена 2 канала использовать: 1 на прием, 2 на передачу?

**Comment by mitskovets** [comment]
> Наткулся на статью https://habr.com/post/354754/ именно этот паттерн я предлагаю использовать.
Прикольно, очень понравилось, такой же нужно делать и в МК

**Comment by serjrv** [comment]
А что в этой статье прикольного, ну изобрел человек в сотый раз колесо... В контроллере все и сделано независимо, есть датчик, он опрашивается, нет датчика, ну и черт с ним, контроллер идет дальше трудиться. В "железной" реализации главным является распределение приоритетов между задачами, т.к. к примеру опросим мы датчики ровно через секунду или через полторы, нам все равно, а вот ТЭНом так порулить не выйдет, там нужен четкий временной интервал.

**Comment by mitskovets** [comment]
т.е. что выходит, контроллеру все равно, сколько процессов у него «дергать»?

**Comment by serjrv** [comment]
А в чем проблема с количеством процессов? В нашем случае их очень мало. А просто всегда читать флаги для выполнения события на МК очень глупо, там обычно происходит все проще - сработало соответствующее аппаратное прерывание, выполнили нужную подпрограмму.

**Comment by mitskovets** [comment]
Тогда очевидно я не очень понимаю сути, что на МК будут запущены сразу все процессы, ректификация, дистиляция, пивоварение? Или все же они будут запускаться только когда от веб придет команда? Но тогда это и будет флаг. А, опять же, если процесс нужно сначала конфигурировать, как например для пива.

**Comment by serjrv** [comment]
Мы просто немного о разном говорим. Ответ от WEB проверяется непрерывно, но в свободное от выполнения подпрограмм общающихся с железом (датчики, ТЭН, экран и т.д.). Там естественно уже и проверяется что нам прилетело от пользователя, как итог и начинаем рулить соответствующим процессом. До подпрограмм связанных с WEB я еще не добирался, т.к. в первую очередь надо все общение с железом добить. Но если есть что то срочное, связанное с реализацией WEB на уровне контроллера, пишите, будем делать.

**Comment by mitskovets** [comment]
Из хотелок, для веб, 
1. сделать одну кнопку сохранения настроек, https://github.com/TheLuckyChip/LuckyBox/issues/7 а это в МК сначала нужно сделать, 
2. сделать назначение (название) датчиков и хорошо бы, что бы они там сохранялись
3. у меня нет понимания процессов (ректификат, дистиляция, пиво), что должно (нужно) приходить от МК и что необходимо контролировать, менять (править, ТЭН тот же), соответственно в пивоварении дать возможность сохранения своего рецепта, что бы потом варить по нему, загрузки рецепта (в json) например (я думаю вполне можно, договориться с каким-нибудь форумом впоследствии, для создания АПИ выгрузки рецепта, к примеру http://xn--90aia8b.xn--p1ai/beer_recipes/bjcp_2015), тут опять же в зависимости от процесса, вывод графиков, и например сохранение профилей (количество) датчиков, для каждого процесса, что бы не заводить его каждый раз.

Я же говорю :-) нужна скайп конференция со всеми разработчиками.

**Comment by serjrv** [comment]
Настройки датчиков будут отдельной вкладкой, с настройками WiFi совмещать же не будем? Я тогда попробую завтра вечером это сделать. С рецептами давайте позже разберемся. Тем более думаю их лучше на SD карту сохранять, так и подправить проще, и поделиться.

**Comment by mitskovets** [comment]
Да, настройки датчиков отдельно

**Comment by TheLuckyChip** [comment]
С рецептами и API с сайта - идея очень правильная. На будущее надо будет сделать обязательно, тоотко ответственно к выбору сайта подойти, или группы сайтов. Бомба получится!

**Comment by TheLuckyChip** [comment]
Сергей mitskovets, я поправил один косячок в heater.js. Выложил в Dev. Обрати пожалуйста внимание при создании web- интерфейса.
