### ISSUE TITLE
Единый запрос состояния МК для всех процессов

### ISSUE THREAD

**Issue by Sivolday** [TheLuckyChip/LuckyBox#4]
Под состоянием я понимаю: показание всех датчиков, установленную мощность, настойки… в данный момент времени.

Сл. функции делают запросы к серверу:

- **getSettings()**
- **getDistillation()**
- **getReflux()**
- **getPower()**
- **getBrewing()**

Это не правильно и перегружает код в МК. сейчас идёт 2 запроса по сути с дублируемым содержанием.

1. Предлагаю делать одни запрос, что бы получить состояние МК, состояние предавать через configs.json. Каждый процесс (дислияция, ректификация…) будет интерпретировать показания по своему усмотрению.
2. На клиенте накапливать состояния в массиве. Каждый процесс будет брать последний элемент из массива который лежит в глобальной области видимости. Это позволит сделать лог и графики.

То есть постоянно крутиться: **setTimeout(getSettings, 2000);**
И в какаято из функций 
- **distillation()**
- **reflux()**
- **power()**
- **brewing()**

**Comment by mitskovets** [comment]
Согласен конечно, об этом писал уже. У процесса нужно делать запуск. А по сути там всегда одни данные — показания датчиков. Нужно считаю идти от контролера, сделать сервис там, а под него допилить веб часть.

**Comment by TheLuckyChip** [comment]
В принципе да, количество датчиков конечно, они все опрашиваются. 
И модульность наверное можно соблюсти. Если модуль подключен, то обновляет данные, а не подключен, то константы. Хотя этот момент надо продумать.
