### ISSUE TITLE
Сброс настоек при вводе

### ISSUE THREAD

**Issue by Sivolday** [TheLuckyChip/LuckyBox#6]
В текущей реализации, настройки обновляются раз в две секунды, невозможно осуществить ввод, введённые данные сбрасываются, надо крайне ловко жать кнопку submit.

`
      setTimeout(getSettings, 2000);

	function getSettings() {
		$.ajax({
			url: 'configs.json',
			data: {},
			type: 'GET',
			dataType: 'json',
			success: function (msg) {
				console.log('Settings',msg);
				$("#settings_ssdp").val(msg["SSDP"]);
				$("#settings_ssid").val(msg["ssid"]);
				$("#settings_password").val(msg["password"]);
				$("#settings_ssidap").val(msg["ssidAP"]);
				$("#settings_passwordap").val(msg["passwordAP"]);
				$("#settings_timezone").val(msg["timezone"]);

				setTimeout(getDistillation, 2000);
			}
		});
	}
`

Я уже предлагал накапливать состояния МК в массиве, если это реализовать можно сравнивать с предпоследним состоянием, обновлять интерфейс только в случае изменения и при переходе на страницу настроек.

**Comment by mitskovets** [comment]
Ага, уже заметил это, нужно подумать, да. Вечером займусь.
