### ISSUE TITLE
Сделать одну кнопку submit

### ISSUE THREAD

**Issue by Sivolday** [TheLuckyChip/LuckyBox#7]
Предлагаю сделать одну кнопку. В противном случае количество кода растёт, в том числе и на МК. Настроек будет гораздо больше.

[Скрин](https://www.dropbox.com/s/ucbcc3hxmune60n/OneButon.png?dl=0)

**Comment by mitskovets** [comment]
Согласен, кто изменит сервис в МК?

**Comment by Sivolday** [comment]
Постараюсь за ближайший день сформировать 2 DTO объекта (JSON), clientToServer и ServerToClient их можно принять за интерфейс.

**Comment by mitskovets** [comment]
Там все бы на JSON перевести, а то там и JSON и TEXT
